# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: meeting-transcriber

before:
  hooks:
    - cp -r bin/meeting-transcriber.app meeting-transcriber.app

builds:
  - id: meeting-transcriber
    main: .
    binary: meeting-transcriber
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-mmacosx-version-min=10.15
      - CGO_LDFLAGS=-mmacosx-version-min=10.15
    flags:
      - -trimpath
    tags:
      - production
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: "meeting-transcriber.app/**"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: dannygim
    name: meeting-transcriber
  draft: false
  prerelease: auto
