# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: meeting-transcriber

before:
  hooks:
    - cp -r bin/meeting-transcriber.app meeting-transcriber.app

builds:
  - id: meeting-transcriber
    main: .
    binary: meeting-transcriber
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-mmacosx-version-min=10.15
      - CGO_LDFLAGS=-mmacosx-version-min=10.15
    flags:
      - -trimpath
    tags:
      - production
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: "meeting-transcriber.app/**"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: dannygim
    name: meeting-transcriber
  draft: false
  prerelease: auto

homebrew_casks:
  - name: meeting-transcriber
    repository:
      owner: dannygim
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/dannygim/meeting-transcriber"
    description: "On-device meeting audio transcription app powered by whisper.cpp"
    dependencies:
      - formula: portaudio
      - formula: whisper-cpp
    caveats: |
      You need to download a Whisper model:
        mkdir -p ~/models && curl -L -o ~/models/ggml-large-v3.bin \
          https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin

      Since this app is unsigned, you may need to allow it in:
        System Preferences > Security & Privacy
    uninstall:
      quit:
        - com.dannygim.meeting-transcriber
