# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: meeting-transcriber

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: dannygim
    name: meeting-transcriber
  draft: false
  prerelease: auto
  extra_files:
    - glob: "meeting-transcriber_*.zip"
    - glob: "checksums.txt"
