import { useState, useEffect, useRef, useCallback } from 'react'

// Bindings will be auto-generated by wails3 generate bindings
import { AudioService } from '../../bindings/github.com/dannygim/meeting-transcriber/services'

export type RecordingState = 'idle' | 'recording' | 'paused' | 'transcribing'

export function useRecorder() {
  const [state, setState] = useState<RecordingState>('idle')
  const [elapsed, setElapsed] = useState(0)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const startTimer = useCallback(() => {
    if (timerRef.current) clearInterval(timerRef.current)
    timerRef.current = setInterval(async () => {
      try {
        const t = await AudioService.GetElapsedTime()
        setElapsed(t)
      } catch {
        // ignore polling errors
      }
    }, 200)
  }, [])

  const stopTimer = useCallback(() => {
    if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }
  }, [])

  useEffect(() => {
    return () => stopTimer()
  }, [stopTimer])

  const startRecording = useCallback(async () => {
    await AudioService.StartRecording()
    setState('recording')
    setElapsed(0)
    startTimer()
  }, [startTimer])

  const pauseRecording = useCallback(async () => {
    await AudioService.PauseRecording()
    setState('paused')
  }, [])

  const resumeRecording = useCallback(async () => {
    await AudioService.ResumeRecording()
    setState('recording')
  }, [])

  const stopRecording = useCallback(async (): Promise<string> => {
    stopTimer()
    const wavPath = await AudioService.StopRecording()
    setState('idle')
    return wavPath
  }, [stopTimer])

  const setTranscribing = useCallback(() => {
    setState('transcribing')
  }, [])

  const setIdle = useCallback(() => {
    setState('idle')
  }, [])

  return {
    state,
    elapsed,
    startRecording,
    pauseRecording,
    resumeRecording,
    stopRecording,
    setTranscribing,
    setIdle,
  }
}
