// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetElapsedTime() {
    return $Call.ByID(2109600758);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetRecordingState() {
    return $Call.ByID(3883308101);
}

/**
 * GetSpectrum returns frequency band magnitudes (0.0-1.0) for visualization.
 * Uses logarithmic frequency scaling focused on the voice range (80Hz-12kHz).
 * @returns {$CancellablePromise<number[]>}
 */
export function GetSpectrum() {
    return $Call.ByID(1574354510).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PauseRecording() {
    return $Call.ByID(119760842);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResumeRecording() {
    return $Call.ByID(3648636639);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartRecording() {
    return $Call.ByID(3651433100);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function StopRecording() {
    return $Call.ByID(1471441810);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
