// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetElapsedTime(): $CancellablePromise<number> {
    return $Call.ByID(2109600758);
}

export function GetRecordingState(): $CancellablePromise<string> {
    return $Call.ByID(3883308101);
}

/**
 * GetSpectrum returns frequency band magnitudes (0.0-1.0) for visualization.
 * Uses logarithmic frequency scaling focused on the voice range (80Hz-12kHz).
 */
export function GetSpectrum(): $CancellablePromise<number[]> {
    return $Call.ByID(1574354510).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PauseRecording(): $CancellablePromise<void> {
    return $Call.ByID(119760842);
}

export function ResumeRecording(): $CancellablePromise<void> {
    return $Call.ByID(3648636639);
}

export function StartRecording(): $CancellablePromise<void> {
    return $Call.ByID(3651433100);
}

export function StopRecording(): $CancellablePromise<string> {
    return $Call.ByID(1471441810);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
