// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelDownload() {
    return $Call.ByID(2092928170);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DownloadModel(name) {
    return $Call.ByID(188242269, name);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetModelsDir() {
    return $Call.ByID(2924884261);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDownloading() {
    return $Call.ByID(926214416);
}

/**
 * @returns {$CancellablePromise<$models.ModelInfo[]>}
 */
export function ListModels() {
    return $Call.ByID(3496170258).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ModelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
