// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetModelPath() {
    return $Call.ByID(789002356);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsWhisperAvailable() {
    return $Call.ByID(1105140019);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function RefreshModelPath() {
    return $Call.ByID(1265595517);
}

/**
 * @param {string} lang
 * @returns {$CancellablePromise<void>}
 */
export function SetLanguage(lang) {
    return $Call.ByID(2046496696, lang);
}

/**
 * @param {string} wavPath
 * @returns {$CancellablePromise<string>}
 */
export function Transcribe(wavPath) {
    return $Call.ByID(98010101, wavPath);
}

/**
 * @param {string} wavPath
 * @returns {$CancellablePromise<string>}
 */
export function TranscribeToFile(wavPath) {
    return $Call.ByID(1569112770, wavPath);
}
