// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetModelPath(): $CancellablePromise<string> {
    return $Call.ByID(789002356);
}

export function IsWhisperAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(1105140019);
}

export function SetLanguage(lang: string): $CancellablePromise<void> {
    return $Call.ByID(2046496696, lang);
}

export function Transcribe(wavPath: string): $CancellablePromise<string> {
    return $Call.ByID(98010101, wavPath);
}

export function TranscribeToFile(wavPath: string): $CancellablePromise<string> {
    return $Call.ByID(1569112770, wavPath);
}
